### ISSUE TITLE
Comparison of "Zalgo text"

### ISSUE THREAD

**Issue by BrandonKMLee** [kdex/unzalgo#34]
There are other repos that has different character list for Zalgo, what are the major difference between them? Also why are they categorized by the positions they are in?
- https://github.com/hackvertor/visualfuzzer/blob/master/visualfuzzer.js#L56
- https://github.com/Marak/zalgo.js/blob/master/zalgo.js#L3
- https://github.com/kortschak/zalgo/blob/master/zalgo.go#L35
- https://github.com/Kimbatt/js-Z/blob/gh-pages/main.ts#L149
- https://github.com/gregoryneal/zalgo/blob/master/code/zalgo_text/zalgo.py#L11
- https://github.com/michaelrhodes/to-zalgo/blob/master/lib/chars.js#L2

**Comment by kdex** [comment]
I guess many people are using the word "Zalgo" as an umbrella term for garbled text. It's not as if there's a clear standard that defines what is and what isn't considered Zalgo text.

There can be many reasons why some people define their own list of Zalgo characters or even categorize the graphemes into visual groups:

- They want to ascertain a desired visual effect on the output string.
- They want to be able to test the program and trust that it doesn't generate any weird, unexpected output.
- Checking whether or not a given symbol is part of a certain [Unicode character category](https://www.unicode.org/reports/tr49/Categories.txt) through ECMAScript is easy nowadays by using a one-liner, but doing the opposite requires a bit more code. "The opposite" being to create an array that contains a list of all characters in a given category. This isn't something I'd expect novice programmers to just grasp and implement in a couple of minutes, so many will just hard-code a set of Zalgo characters, since they simply don't know any better.
- They want to ship an array of Zalgo characters in their library, but without computing it during runtime. This requires some pre-computation during build time, and some people just don't have the time, the patience, or the experience to set up a custom build pipeline to do that, and others simply don't care about optimizing their libraries that much.

So as long as Zalgo text isn't standardized (which I doubt it ever will be), from an engineering perspective, you're going to have to assume that, given enough time, there will be at least as many definitions of "Zalgo" as there are people on this planet.

The definition that I personally go by is that Zalgo characters are characters in the `Mn (Mark, Nonspacing)` or `Me (Mark, Enclosing)` categories. I believe that this view is pretty generalized, and it has worked well for this library so far, but I'm willing to change my perspective given new evidence.
